### ISSUE TITLE
完成させなければならない件

### ISSUE THREAD

**Issue by lalaso2000** [nitgc-comb/hp#1]
旧HPが[高専の公式サイト](http://www.gifu-nct.ac.jp/campuslife/club/)からリンク切れになってしまったので，本サイトがリンクされる予定です．
それまでにはとりあえずver 1.0を完成させなければならない…

**Comment by prismistim** [comment]
😇

**Comment by lalaso2000** [comment]
ひとまず…難は逃れたということで
